version: '2.0'
services:
  web:
    image: onlineshop_aspnetcore_reactjs:latest
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
        - "27017:27017"
